### ISSUE TITLE
weight oscilation code

### ISSUE THREAD

**Issue by qiulinzhang** [Qualcomm-AI-research/oscillations-qat#4]
Thanks for your great work. I have a problem in code "oscillation_tracking_utils.py", where `self.ema_x_int`  and `self.frozen_x_int` are never used in any other place. the `__call__` function of class `TrackOscillation` also still returns `x_int`, instead of  `self.ema_x_int`, which seems the weight oscillation is not dampened.

**Comment by rainyBJ** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/49946568/183450336-34b4c57c-f368-4dab-93a0-ab035657e405.png">
In line 56, 57. The frozen operation is applied. So the returned value x_int, is already frozened.

**Comment by rainyBJ** [comment]
> Thanks for your great work. I have a problem in code "oscillation_tracking_utils.py", where `self.ema_x_int` and `self.frozen_x_int` are never used in any other place. the `__call__` function of class `TrackOscillation` also still returns `x_int`, instead of `self.ema_x_int`, which seems the weight oscillation is not dampened.
![image](https://user-images.githubusercontent.com/49946568/183451020-cd58727a-da21-4380-aa75-762087198da4.png)
In line 56, 57. The frozen operation is applied. So the returned value x_int, is already frozened.

**Comment by qiulinzhang** [comment]
> > Thanks for your great work. I have a problem in code "oscillation_tracking_utils.py", where `self.ema_x_int` and `self.frozen_x_int` are never used in any other place. the `__call__` function of class `TrackOscillation` also still returns `x_int`, instead of `self.ema_x_int`, which seems the weight oscillation is not dampened.
> > ![image](https://user-images.githubusercontent.com/49946568/183451020-cd58727a-da21-4380-aa75-762087198da4.png)
> > In line 56, 57. The frozen operation is applied. So the returned value x_int, is already frozened.

Thanks for kind reply. That means x_int will be frozen from the last osillation track, rather than the current oscillation track, which maybe won't cause problem and only make the statistics of the final oscillation track waste.

**Comment by rainyBJ** [comment]
> > > Thanks for your great work. I have a problem in code "oscillation_tracking_utils.py", where `self.ema_x_int` and `self.frozen_x_int` are never used in any other place. the `__call__` function of class `TrackOscillation` also still returns `x_int`, instead of `self.ema_x_int`, which seems the weight oscillation is not dampened.
> > > ![image](https://user-images.githubusercontent.com/49946568/183451020-cd58727a-da21-4380-aa75-762087198da4.png)
> > > In line 56, 57. The frozen operation is applied. So the returned value x_int, is already frozened.
> 
> Thanks for kind reply. That means x_int will be frozen from the last osillation track, rather than the current oscillation track, which maybe won't cause problem and only make the statistics of the final oscillation track waste.

Yes, this oscillation track happens every iteration of training(when the self.frozen flag is set to True by a CosineTempDecay scheduler) and the whole training process can have dozens of epochs, lots of iterations, so wasting the final oscillation track is just not a big deal.
